runtime: python

# the PROJECT-DIRECTORY is the one with settings.py and wsgi.py
entrypoint: gunicorn -b :$PORT pathways_rest.wsgi # specific to a GUnicorn HTTP server deployment
env: flex # for Google Cloud Flexible App Engine

handlers:
  - url: /static
    static_dir: static

beta_settings:
  # from command >> gcloud sql instances describe DATABASE-NAME <<
  cloud_sql_instances: PROJECT-ID:COMPUTE-ENGINE-ZONE:pathways-database

runtime_config:
  python_version: 3 # enter your Python version BASE ONLY here. Enter 2 for 2.7.9 or 3 for 3.6.4
